### ISSUE TITLE
Pythonになれる

### ISSUE THREAD

**Issue by haruya3** [Level-up-geek/LineBot#1]
pythonコードで入力された値をオウム返しで出力する。
(例)
(入力はコンソール(コマンドプロンプト、ターミナル)から受け取る)
入力ー＞1
・
・
・
出力ー＞1

**Comment by haruya3** [comment]
入力が文字列だったらなにもせず出力。
数値だったら文字列から数値型にして出力。

**Comment by sAtOr-i7** [comment]
終わりました。
https://colab.research.google.com/drive/1HiK4PIKQ9wf8342ebP1C_lZ2xHzoR9gp?usp=sharing
